version: '2'
services:
  ng8booot-app:
    image: ng8booot
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://ng8booot-mysql:3306/ng8booot?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8000:8000
  ng8booot-mysql:
    extends:
      file: mysql.yml
      service: ng8booot-mysql
